//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlickCMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Relationship
    {
        public int RelationshipID { get; set; }
        public int CategoryID { get; set; }
        public int LinkID { get; set; }
        public int PostID { get; set; }
        public int UserID { get; set; }
        public int TagID { get; set; }
        public int Order { get; set; }
    }
}
